- name: Add mosquitto repo
  apt_repository:
    repo: ppa:mosquitto-dev/mosquitto-ppa
    state: present

- name: Install mosquitto packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - mosquitto
    - mosquitto-clients

- name: Add mosquitto service
  systemd:
    state: started
    name: mosquitto 
    enabled: yes

- name: Allow MQTT Unsecure in through the firewall
  ufw:
    rule: allow
    port: 1883
    proto: tcp

- name: Allow MQTT HTTPS in through the firewall
  ufw:
    rule: allow
    port: 1884
    proto: tcp

- name: Allow MQTT Websocket in through the firewall
  ufw:
    rule: allow
    port: 8883
    proto: tcp
