- name: Add an APT key for Node Repo
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add Node Repo
  apt_repository:
    repo: deb https://deb.nodesource.com/node_10.x bionic main
    state: present
    filename: nodesource.list 

- name: Install NodeJS
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - yarn
    - nodejs
