- name: Creates organizr data directory
  file:
    path: /opt/organizr
    state: directory
    owner: hass
    group: hass
    mode: 0755
    recurse: yes

- name: Install Organizr
  docker_container:
    name: organizr
    image: linuxserver/organizr
    state: started
    ports:
    - "8080:80"
    volumes:
    - /opt/organizr:/config
    env:
      PUID: "1001"
      PGID: "1001"
      TZ: "Europe/London"

- name: Allow Organizr in through the firewall
  ufw:
    rule: allow
    port: 8080
    proto: tcp
