- name: Install Portainer
  docker_container:
    name: portainer
    image: portainer/portainer
    state: started
    ports:
    - "9000:9000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

- name: Allow Portainer in through the firewall
  ufw:
    rule: allow
    port: 9000
    proto: tcp
