- name: Remove the password for sudo group when sudo'ing
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add manager user to sudo group
  user:
    name: manager
    groups: sudo
    append: yes

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
