##### Docker Stuff
- name: Add an APT key for Docker Repo
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
    filename: docker-ce.list

- name: Install Docker
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io

- name: Add manager user to docker group
  user:
    name: manager
    groups: docker
    append: yes

- name: Add hass user to docker group
  user:
    name: hass
    groups: docker
    append: yes

- name: Make sure the docker service is running
  systemd:
    state: started
    name: docker
    enabled: yes
